---
# tasks file for miniconda
- name: download installer.sh
  get_url: >
    url={{miniconda_installer_url}}
    dest=/tmp/{{miniconda_installer_sh}}
    owner=root
    group=root
    mode=0755

- name: installing conda
  command: /tmp/{{miniconda_installer_sh}} -b -p /opt/{{miniconda_name}}
  args:
    creates: /opt/{{miniconda_name}}/bin/conda

- name: deleting installer...
  when: miniconda_cleanup
  file:
    path=/tmp/{{miniconda_installer_sh}}
    state=absent
    
- name: link miniconda...
  file:
    dest=/opt/miniconda
    src=/opt/{{miniconda_name}}
    state=link
    owner=root
    group=root

- name: conda updates
  command: /opt/miniconda/bin/conda update -y {{item}}
  with_items: '{{ miniconda_pkg_list }}'

- name: make system default python etc...
  when: miniconda_make_sys_default
  copy: >-
    src=etc/profile.d/miniconda.sh
    dest=/etc/profile.d/miniconda.sh
    mode=0644
    owner=root
    group=root
    
